import React, { PropsWithChildren } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const Layout = ({ children }: PropsWithChildren) => {
  return (
    <html>
      <head>
        <title>marionursalim</title>
          <meta content="width=device-width, initial-scale=1" name="viewport" />
          <meta name="description" content="Generated by create next app" />
          <link
            rel="icon"
            href="/Ayamayam.jpg/"
          />
      </head>
      <body>
        <Navbar />
        <div>{children}</div>
        <Footer/>
      </body>
    </html>
  );
};

export default Layout;
